name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HG: ${{ secrets.HG }}
        run: |
          git remote add space https://saaib:${HG}@huggingface.co/spaces/saaib/HG
          git remote -v  # Verify the remote configuration
      - name: Push to hub
        env:
          HG: ${{ secrets.HG }}
        run: git push --force space main
